project:
  type: website
  output-dir: docs
  
website:
  title: "blog"
  navbar:
    left: 
      - text: Home
        href: https://hemu0626.github.io
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/mu-he-63463767/
      - icon: github
        text: Github
        href: https://github.com/hemu0626
     # - icon: instagram
    #    text: Instagram
    #    href: https://www.instagram.com/muuu9312/
format:
  html:
    theme: cosmo
    css: styles.css
  
editor: visual

